# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish driver

# FIXME
# npm token kep raising as invalid while it had proper one.
on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#    # paths:
#    #   - 'driver/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        working-directory: driver
      - run: npm test
        working-directory: driver

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm install
        working-directory: driver
      - name: update npm-shrinkwrap.json
        working-directory: driver
        run: |
          rm npm-shrinkwrap.json
          npm prune --production
          rm -rf node_modules/appium
          npm shrinkwrap
          git diff
      - run: npm install --only=dev
        name: Install dev dependencies for the release
        working-directory: driver
      - run: npx semantic-release --branches main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # to make the push failure
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Release
        working-directory: driver
